"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const ANKI_VEHICLE_MSG_BASE_SIZE = 1;
exports.ANKI_VEHICLE_MSG_BASE_SIZE = ANKI_VEHICLE_MSG_BASE_SIZE;
// BLE Connections
const ANKI_VEHICLE_MSG_C2V_DISCONNECT = 0x0d;
exports.ANKI_VEHICLE_MSG_C2V_DISCONNECT = ANKI_VEHICLE_MSG_C2V_DISCONNECT;
// Ping request / response
const ANKI_VEHICLE_MSG_C2V_PING_REQUEST = 0x16;
exports.ANKI_VEHICLE_MSG_C2V_PING_REQUEST = ANKI_VEHICLE_MSG_C2V_PING_REQUEST;
const ANKI_VEHICLE_MSG_V2C_PING_RESPONSE = 0x17;
exports.ANKI_VEHICLE_MSG_V2C_PING_RESPONSE = ANKI_VEHICLE_MSG_V2C_PING_RESPONSE;
// Messages for checking vehicle version info
const ANKI_VEHICLE_MSG_C2V_VERSION_REQUEST = 0x18;
exports.ANKI_VEHICLE_MSG_C2V_VERSION_REQUEST = ANKI_VEHICLE_MSG_C2V_VERSION_REQUEST;
const ANKI_VEHICLE_MSG_V2C_VERSION_RESPONSE = 0x19;
exports.ANKI_VEHICLE_MSG_V2C_VERSION_RESPONSE = ANKI_VEHICLE_MSG_V2C_VERSION_RESPONSE;
// Battery level
const ANKI_VEHICLE_MSG_C2V_BATTERY_LEVEL_REQUEST = 0x1a;
exports.ANKI_VEHICLE_MSG_C2V_BATTERY_LEVEL_REQUEST = ANKI_VEHICLE_MSG_C2V_BATTERY_LEVEL_REQUEST;
const ANKI_VEHICLE_MSG_V2C_BATTERY_LEVEL_RESPONSE = 0x1b;
exports.ANKI_VEHICLE_MSG_V2C_BATTERY_LEVEL_RESPONSE = ANKI_VEHICLE_MSG_V2C_BATTERY_LEVEL_RESPONSE;
// Lights
const ANKI_VEHICLE_MSG_C2V_SET_LIGHTS = 0x1d;
exports.ANKI_VEHICLE_MSG_C2V_SET_LIGHTS = ANKI_VEHICLE_MSG_C2V_SET_LIGHTS;
// Driving Commands
const ANKI_VEHICLE_MSG_C2V_SET_SPEED = 0x24;
exports.ANKI_VEHICLE_MSG_C2V_SET_SPEED = ANKI_VEHICLE_MSG_C2V_SET_SPEED;
const ANKI_VEHICLE_MSG_C2V_CHANGE_LANE = 0x25;
exports.ANKI_VEHICLE_MSG_C2V_CHANGE_LANE = ANKI_VEHICLE_MSG_C2V_CHANGE_LANE;
const ANKI_VEHICLE_MSG_C2V_CANCEL_LANE_CHANGE = 0x26;
exports.ANKI_VEHICLE_MSG_C2V_CANCEL_LANE_CHANGE = ANKI_VEHICLE_MSG_C2V_CANCEL_LANE_CHANGE;
// Vehicle position updates
const ANKI_VEHICLE_MSG_V2C_LOCALIZATION_POSITION_UPDATE = 0x27;
exports.ANKI_VEHICLE_MSG_V2C_LOCALIZATION_POSITION_UPDATE = ANKI_VEHICLE_MSG_V2C_LOCALIZATION_POSITION_UPDATE;
const ANKI_VEHICLE_MSG_V2C_LOCALIZATION_TRANSITION_UPDATE = 0x29;
exports.ANKI_VEHICLE_MSG_V2C_LOCALIZATION_TRANSITION_UPDATE = ANKI_VEHICLE_MSG_V2C_LOCALIZATION_TRANSITION_UPDATE;
const ANKI_VEHICLE_MSG_V2C_LOCALIZATION_INTERSECTION_UPDATE = 0x2a;
exports.ANKI_VEHICLE_MSG_V2C_LOCALIZATION_INTERSECTION_UPDATE = ANKI_VEHICLE_MSG_V2C_LOCALIZATION_INTERSECTION_UPDATE;
const ANKI_VEHICLE_MSG_V2C_VEHICLE_DELOCALIZED = 0x2b;
exports.ANKI_VEHICLE_MSG_V2C_VEHICLE_DELOCALIZED = ANKI_VEHICLE_MSG_V2C_VEHICLE_DELOCALIZED;
const ANKI_VEHICLE_MSG_C2V_SET_OFFSET_FROM_ROAD_CENTER = 0x2c;
exports.ANKI_VEHICLE_MSG_C2V_SET_OFFSET_FROM_ROAD_CENTER = ANKI_VEHICLE_MSG_C2V_SET_OFFSET_FROM_ROAD_CENTER;
const ANKI_VEHICLE_MSG_V2C_OFFSET_FROM_ROAD_CENTER_UPDATE = 0x2d;
exports.ANKI_VEHICLE_MSG_V2C_OFFSET_FROM_ROAD_CENTER_UPDATE = ANKI_VEHICLE_MSG_V2C_OFFSET_FROM_ROAD_CENTER_UPDATE;
// Turn Command
const ANKI_VEHICLE_MSG_C2V_TURN = 0x32;
exports.ANKI_VEHICLE_MSG_C2V_TURN = ANKI_VEHICLE_MSG_C2V_TURN;
// Light Patterns
const ANKI_VEHICLE_MSG_C2V_LIGHTS_PATTERN = 0x33;
exports.ANKI_VEHICLE_MSG_C2V_LIGHTS_PATTERN = ANKI_VEHICLE_MSG_C2V_LIGHTS_PATTERN;
// Vehicle Configuration Parameters
const ANKI_VEHICLE_MSG_C2V_SET_CONFIG_PARAMS = 0x45;
exports.ANKI_VEHICLE_MSG_C2V_SET_CONFIG_PARAMS = ANKI_VEHICLE_MSG_C2V_SET_CONFIG_PARAMS;
// SDK Mode
const ANKI_VEHICLE_MSG_C2V_SDK_MODE = 0x90;
exports.ANKI_VEHICLE_MSG_C2V_SDK_MODE = ANKI_VEHICLE_MSG_C2V_SDK_MODE;
const ANKI_VEHICLE_SDK_OPTION_OVERRIDE_LOCALIZATION = 0x1;
exports.ANKI_VEHICLE_SDK_OPTION_OVERRIDE_LOCALIZATION = ANKI_VEHICLE_SDK_OPTION_OVERRIDE_LOCALIZATION;
